name: user_list_task
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4

  cupertino_icons: ^1.0.2
  envied: ^0.5.2
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  injectable: ^2.3.2
  provider: ^6.1.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  envied_generator: ^0.5.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
